### ISSUE TITLE
롯데닷컴

### ISSUE THREAD

**Issue by ScottyKim** [hooriza/oxy-blocker#1]
네이버에서 현재 "옥시"로 검색시
Search 에서 -> 옥시 제습제 표백제 섬유유연제 세...
이 부분은 걸리지 않네요.
소스 보니깐 /옥시/i.test(str) && 다음이 좀 유연하지 않은거 같은데.
여기 우선 뭐 더 추가 해야 할거 같네요.

다른 아이디어는
제품 카테고리 검색 후, 거기에 "옥시"가 있는지 확인 하는 방법도 좋을 듯 합니다. 👍

**Comment by hooriza** [comment]
"옥시" 로 거르면 애먼 상품이 인식 될 우려가 있어서 구체적인 상품명으로만 인식했는데요,
"옥시 제습제", "옥시 표백제", "옥시 섬유유연제" 같은 패턴도 나름 구체적이니 이것도 인식 할 수 있도록 추가할께요~

**Comment by hooriza** [comment]
0.3 으로 릴리즈했어요~ 감사합니다 ㅎㅎ

**Comment by ScottyKim** [comment]
최고
