### ISSUE TITLE
불스원에서 부탁의 말씀을 드립니다.

### ISSUE THREAD

**Issue by bullsone** [hooriza/oxy-blocker#14]
안녕하세요, 자동차 용품 전문 회사 불스원입니다.

우연히 선생님께서 개발하신 ‘옥시 블로커’ 프로그램에
저희 제품이 포함되어 있는 것을 발견하였습니다.

이 프로그램이 차단하는 상품 목록에서 저희 제품을 제외해 주십사 부탁드리고자 합니다.

저희 불스원과 저희 회사의 제품은 가습기 살균제 사건과는 무관합니다.
비록, 한 주주의 과거 이력으로 인해 이번 사태에 대해 연루된 것으로 오해를 사고 있지만
저희 회사는 옥시레킷벤키저와는 다른 별도의 기업입니다.

가습기 살균제 피해자와 가족모임 및 참여연대 등 불매 운동을 전개하고 있는 단체들에서도
저희 제품을 불매 운동 대상으로 올리지 않고 있다는 점 역시 감안해 주셨으면 합니다.

많은 분들이 큰 고통을 당하신 이번 사건을 앞에 두고
자칫 이기적으로 보일 수 있는 부탁을 드리는 것에 대해 깊은 고민을 했지만
오해들이 쌓여 감당하기 어려운 큰 위기로 번지고 있는 상황에서
작은 노력부터 해야겠다는 생각에 부탁을 드리게 되었습니다.

모쪼록, 저희 회사가 돌이킬 수 없는 상처를 입지 않도록
배려해주시기를 간곡하게 청합니다.

감사합니다.

**Comment by hooriza** [comment]
올리신 이슈 확인이 늦었네요. 말씀하신 것처럼 불스원의 제품은 불매 운동 대상이 아닌것으로 확인되어 해당 제품은 차단 대상에서 제외하고 릴리즈 했습니다. 감사합니다.
